### ISSUE TITLE
Places, what are they and how should they be implemented?

### ISSUE THREAD

**Issue by digisomni** [vircadia/Iamus#67]
Currently, "places" or "locations" are handled by beacon entities placed in your domain that report to a relay server completely unrelated to the metaverse.

The route that High Fidelity went with "places" was to have them treated like domain names are on the internet. Each one is purchased on the metaverse and completely unique in name. A place name then is valuable as it is unique like a domain name. A place name then can be assigned and reassigned to any domain that you wish.

**Comment by JulianGro** [comment]
Something that is probably worth considering is the end result we want.
Personally I would want to select which world to go to, which instance of that world and which place in that world.

A little example here: The Hub has two places, the main island and the boat. At some point we will probably want multiple instances. (If not for the Hub, more private places like some kind of meeting world would profit more from having multiple smaller instances)

In this scenario Explore would need to know how many users are on a Domain and in which places they are. If there is multiple instances, it could just add them up. (I know that there currently is no proper system for multiple instances) Same for the maximum amount of allowed users if limited. Explore would also need to know the names of the Domain (and maybe instances of it, since you might want to have an instance in the US and one in the EU for example) and the names of the places, so it can search through Domain- and place-names. Obviously people could just have multiple Domains without an instance system, it just seems nicer to at least have the option for a system like that in the future, since having multiple of the same Domains in Explore would make it quite messy.

Here is a little mockup to how that could look to an end user: 
![vircadia-snap-by-motofckr9k-on-2020-12-17_23-58-43_mockup](https://user-images.githubusercontent.com/11144627/102561947-4503fb80-40d6-11eb-96a3-afea48aa716f.png)

**Comment by digisomni** [comment]
A way to offload the data structure of places from the Metaverse Server would be to have the Domain Servers report the information to the metaverse as metadata and let clients parse metadata for places. This way its structure and implementation can evolve independently.

**Comment by AleziaKurdis** [comment]
A place is basically a container for a landing point in a specific domain
in your example there are 4 places
and sort them by their Domain won't be relevant in every cases.
As some user will have many different and unrelated worlds stored in a same domain.
If some grouping is desired, I think we should not tied to domain, but on any semantic tagging or categorization.

**Comment by ctrlaltdavid** [comment]
How about considering things from the point of view of URL addresses.

Current URL schemes supported are as follows…

Position in current domain:
/path
/position/orientation
Optional: orientation

DNS addresses:
hifi://localhost/path
hifi://n.n.n.n:port/path
hifi://domain.tld:port/path
hifi://subdomain.domain.tld:port/path
hifi://localhost/position/orientation
hifi://n.n.n.n:port/position/orientation
hifi://domain.tld:port/position/orientation
hifi://subdomain.domain.tld:port/position/orientation
Optional: hifi, port, path, position, orientation
Note: Paths are defined in the server settings’ “Content” tab.

Vircadia addresses:
hifi://domain/path
hifi://domain/position/orientation
hifi://place/position/orientation
Optional: hifi, path, position, orientation

User address:
@username

Serverless domains:
file:///<path to JSON file>?location=<location>
http://<path to JSON file>?location=<location>
https://<path to JSON file>?location=<location>
Optional: location

Reference: `AddressManager::handleUrl()`


Q: What to do about Vircadia domains, placenames, and beacons?
- Beacons, while convenient, are ripe for griefing. E.g., what say I add 10,000 beacons to my domain just because I can? Perhaps beacons should be done away with?
- Placenames were created by High Fidelity as an alternative “domain name system”, that they could sell place names on. It’s sounding like people are thinking that Vircadia doesn’t really need these or want their complication.
- Domain names are useful, both for domain owners to identify domains by and visitors to navigate to. Perhaps domain names can be registered in the metaverse and associated with domain via the domain server’s ID. Domain names should be able to be assigned to other server IDs. And they should persist if the server is deleted (e.g., so that they can be assigned to a new server).
- Perhaps more than one domain name could point to a single domain server.
- Perhaps a domain name could point to a path within the domain server.

Q: How to add in support for federation (i.e., add a field that specifies the metaverse) for:
- DNS addresses. … It’s perhaps just a matter of the domain server reporting the metaverse server that the domain is registered on. 
- Vircadia addresses… Perhaps hifi://domain@metaverse/path, hifi://domain@metaverse/position/orientation
- User address … Perhaps @user@metaverse

Note: when connecting to a domain Users will probably need specify themselves as username@metaverse (or anonymous), or something similar.

**Comment by Misterblue** [comment]
The reasons Places are not a separate discovery service are permissions (limiting who can create places in domains) and Place attendance (number of avatars at the Place). The domain-server is the best one to know attendance and the metaverse-server is the one who knows which accounts are managing the domains. 
A hybrid solution is to have Places created at  the metaverse-server (by the domain owner or managers) and have a Beacon that reports attendance. The binding for the latter could be an access token or other secret that the creator adds to the Place definition and to the beacon. The Beacon is given a location, a radius (for instance), and the secret and the Beacon calls the metaverse-server API with the attendance and the secret to update the place.

**Comment by Misterblue** [comment]
Places have been implemented and there is a Beacon feature where a script can update "current" parameters on the Place (attendance, images, description). Explore is being upgraded to use this Places info.
